SUPABASE_URL = "https://hdbpgxbgrmicfyailrwz.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkYnBneGJncm1pY2Z5YWlscnd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODUwNzYsImV4cCI6MjA4NTM2MTA3Nn0._Vbq4OQxHOkOieKiIrs0JXfMYHSVT45yxnlrm8EWLm4"
DB_HOST = "aws-1-eu-west-1.pooler.supabase.com"
DB_NAME = "postgres"
DB_USER = "postgres.hdbpgxbgrmicfyailrwz"
DB_PASSWORD = "Emov@2025*!"
DB_PORT = "5432"
